### ISSUE TITLE
dependencies are many devdependencies

### ISSUE THREAD

**Issue by cicorias** [MikeHopcroft/ShortOrder#20]
all the `@type/`, chai, etc. are only used at build, etc. time. Not the final library.

**Comment by MikeHopcroft** [comment]
Fixed in  [6156742](https://github.com/MikeHopcroft/ShortOrder/commit/6156742706e2a29896b41a66d5df89c5d48e079c). Let me know if you need me to publish in the near future. Otherwise I will batch a number of changes before publishing.
