### ISSUE TITLE
Translate patterns and demos to Spanish

### ISSUE THREAD

**Issue by MikeHopcroft** [MikeHopcroft/ShortOrder#24]
Translate patterns and demos to Spanish.

The files in question are the yaml files in src/data:

- attributes.yaml
- intents.yaml
- menu.yaml
- quantifiers.yaml
- tests.yaml

It would also be great to get advice on handling special characters, stemming, etc.

**Comment by MikeHopcroft** [comment]
We probably need to have a design discussion around whether we're building a bilingual system or just translating to Spanish. If we're building a bilingual system, we will need to merge the two languages in the yaml files. If we merge the languages, we might want to keep them in separate alias fields to assist the person producing the translations.

**Comment by gmalamuddeb** [comment]
@MikeHopcroft  Will undertake these translations. Will be placed on a new folder in it called Spanish.

**Comment by MikeHopcroft** [comment]
Thanks! I will start thinking about how to integrate another language. Am thinking of adding separate alias fields (e.g. aliases_en, alises_es, etc.) so that one can run bilingual if desired (and if that even works).
