### ISSUE TITLE
Export Token Types

### ISSUE THREAD

**Issue by ryanvolum** [MikeHopcroft/ShortOrder#35]
In order to write an informed parser, I need to be able to distinguish between different kinds of tokens. ```short-order``` exposes a ```printTokens``` function, which utilizes ```AnyToken```, ```UnknownToken```,  ```AttributeToken```, ```EntityToken```, ```IntentToken```, and ```QuantityToken```. Please make these types available so that a custom parser can take advantage of them

**Comment by MikeHopcroft** [comment]
My plan is to factor out the tokenization and place it in a package called `token-flow`. In `token-flow`, the token types will be part of a sample application. The code in `short-order` will then depend on `token-flow` and will define its own, domain-specific tokens which will be exported.

**Comment by MikeHopcroft** [comment]
This should be fixed in the tokenflow branch. Will resolve once I resolve #38.
